version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=serek
      - POSTGRES_DB=LibraryDB
    ports:
      - "5432:5432"
    volumes:
        - type: bind
          source: "/c/Program Files/PostgreSQL/16/data"
          target: /var/lib/postgresql/data/
        - type: bind
          source: "/c/Program Files/PostgreSQL/16/data/postgresql_new.conf"
          target: /var/lib/postgresql/data/postgresql.conf
volumes:
  db:
    driver: local
